### ISSUE TITLE
float32 not supported by xgboost

### ISSUE THREAD

**Issue by kazeevn** [yandex/rep#76] opened 2016-06-22 04:20 UTC
/root/miniconda/envs/rep_py2/lib/python2.7/site-packages/xgboost-0.4-py2.7.egg/xgboost/core.pyc in _maybe_from_pandas(data, feature_names, feature_types)
    151     dtypes = data.dtypes
    152     if not all(dtype.name in ('int64', 'float64', 'bool') for dtype in dtypes):
--> 153         raise ValueError('DataFrame.dtypes must be int, float or bool')
    154 
    155     if feature_names is None:

ValueError: DataFrame.dtypes must be int, float or bool

**Comment by arogozhnikov** [comment] 2016-06-22 06:53
Duplicate of https://github.com/yandex/rep/issues/61

resolved in develop

**Closed by arogozhnikov** 2016-06-22 06:53 UTC
